### ISSUE TITLE
La bottom navbar nella Home dovrebbe gestire Fragments

### ISSUE THREAD

**Issue by ggpslop** [BresciaFrancesco/TourExperience#11]
La bottom navbar nella Home dovrebbe gestire Fragments, e non Activity come fa ora. Di conseguenza l'activity di Home e di lista Musei dovrebbero diventare dei fragments

**Comment by BresciaFrancesco** [comment]
Creato il fragment per la scelta dei musei
Commit: d9ef777b52923eef0c68a10a8204355809977627
