### ISSUE TITLE
La gestione dei permessi causa un crash

### ISSUE THREAD

**Issue by CatignanoFrancesco** [BresciaFrancesco/TourExperience#24]
Quando si accettano i permessi in StanzaFragment per attivare il bluetooth e la geolocalizzazione e si rifiutano subito dopo, si ha un crash del fragment che non riesce ad arrivare nemmeno in onStart(). Non viene segnalato alcun errore e non viene sollevata nessuna eccezione.

**Comment by CatignanoFrancesco** [comment]
Anche spostando la gestione nell'activity, utilizzando le API non deprecate, il bug rimane.

**Comment by FrancolinoFlavioDomenico** [comment]
Si sta procedendo con il ripristino manuale dei valori che servo poichè si è scoperto che il problema è dovuto proprio a un mal rispristino dello stato dell'activity percorso e dei fragment che la compongono

**Comment by FrancolinoFlavioDomenico** [comment]
poichè la causa del problema è la stessa del bug segnalato nella issue #32, questa issue viene chiusa e le commit di risoluzione verranno effettuate in riferimento alla issue #32.
