### ISSUE TITLE
La modalità Landscape nel percorso manda in crash l'app

### ISSUE THREAD

**Issue by ggpslop** [BresciaFrancesco/TourExperience#32]

**Comment by FrancolinoFlavioDomenico** [comment]
poichè la causa del bug è la stessa segnalata nella issue #24 , ovvero il non corretto salvataggio di stato dei frgament in caso di cambi di configurazione, le commit che faranno riferimento al fix di questo bug si considerano valide anche per il fix della issue #24 . Cosi come commit effetuate per fixare  la issue #24 si considerano valide per la fix di questa issue.
