### ISSUE TITLE
Gestione del tasto back in MainActivity

### ISSUE THREAD

**Issue by semifredd0** [BresciaFrancesco/TourExperience#46]
Spostandosi tra i fragment della MainActivity, il backstack non viene gestito correttamente e quando si preme il pulsante back nel fragment SceltaMuseiFragment, l'app va in crash.

**Comment by semifredd0** [comment]
Inoltre ho commentato le animazioni tra i fragments della MainActivity, in quanto spostandosi da StatsFragment a SceltaMuseiFragment, lo slide va da destra verso sinistra, invece dovrebbe essere al contrario

**Comment by ggpslop** [comment]
Il bug sembra essere stato risolto

**Comment by BresciaFrancesco** [comment]
Bug risolto attraverso le precedenti commit
