### ISSUE TITLE
Il quiz non viene riconosciuto

### ISSUE THREAD

**Issue by CatignanoFrancesco** [BresciaFrancesco/TourExperience#48]
Quando si tenta di giocare ad un quiz, anche se presente nella memoria, questo non viene riconosciuto e ne viene richiesta l'importazione da file esterno.

**Comment by ggpslop** [comment]
Il problema sembra essere nella costruzione del path per ottenere il quiz. Il path viene scritto diversamente da come ci si aspetterebbe
