### ISSUE TITLE
Visualizzazione dati nell'app

### ISSUE THREAD

**Issue by semifredd0** [BresciaFrancesco/TourExperience#57]
Il testo presente nei vari JSON contiene alcuni caratteri accentati che non vengono visualizzati correttamente nell'app.
Modificare i relativi file JSON.

**Comment by ggpslop** [comment]
Sul mio dispositivo personale i caratteri accentati vengono visualizzati tutti correttamente. 
Sostituire i caratteri accentati con &egrave non funziona.
