### ISSUE TITLE
Modifiche su Firebase

### ISSUE THREAD

**Issue by semifredd0** [BresciaFrancesco/TourExperience#58]
Eliminare ogni riferimento a Musei Vaticani da Firebase, in quanto non più utilizzato.
Inoltre modificare i nomi dei percorsi di Louvre e Hermitage con nomi realistici, piuttosto che Percorso_1 e Percorso_2.

**Comment by ggpslop** [comment]
Ogni riferimento a Musei Vaticani è stato eliminato da Firebase Storage e Real Time Database

**Comment by ggpslop** [comment]
I nomi del percorsi sono stati modificati ovunque servisse
