### ISSUE TITLE
Immagini non visualizzate nella schermata "Spot the differences"

### ISSUE THREAD

**Issue by semifredd0** [BresciaFrancesco/TourExperience#59]
Le due immagini con le differenze non vengono visualizzate, bug riscontrato in:
- Museo: Hermitage
- Stanza: The gambs hall
- Opera: Woman looking out the window

**Comment by FrancolinoFlavioDomenico** [comment]
il problema era dovuto a un errata denominazione dei file delle immagini di gioco.
Per cui il fix è avvenuto caricando su firebase il zip con la corretta nominazione dei file immagine
