### ISSUE TITLE
Bug nel ripristino dello stato durante il percorso

### ISSUE THREAD

**Issue by BresciaFrancesco** [BresciaFrancesco/TourExperience#64]
Mi trovo in landscape in sceltaStanzeFragment e inquadro il qr ccode della stanza, passo in stanzaFragment. Se poi in stanzaFragment ritorno in portrait, e dopo di che premo il tasto back per tornare in sceltaStanzeFragmentnon la stanza che viene visualizzata è sempre la stessa invece di mostrare la nuova stanza in cui l'utente è entrato

**Comment by CatignanoFrancesco** [comment]
Il bug si verifica quando in SceltaStanzaFragment si è prima in portrait e poi si passa in landscape e si esegue la procedura descritta sopra

**Comment by CatignanoFrancesco** [comment]
Pare che il bug si verifichi in SceltaStanzeFragment. Eseguendo il bug e controllando i log, si scopre che lì l'oggetto path non viene ripristinato correttamente
